# Generated by Django 5.2.5 on 2025-09-15 02:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=accounts.models.generate_otp, max_length=6),
        ),
    ]
