# Generated by Django 5.2.5 on 2025-09-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
    ]
