"""
Django settings for automation_dj project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os

BASE_DIR = Path(__file__).resolve().parent.parent



# ===================== SECURITY =====================

SECRET_KEY = 'django-insecure--gfhi%t8p&0y_zehi_ig6py9%6jk81$gz76z+14%y4ogxt(2xb'
# SECRET_KEY = config("SECRET_KEY", default="django-insecure-placeholder")
# DEBUG = config("DEBUG", default=True, cast=bool)
DEBUG = True
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "https://automation-project-chst.onrender.com",
    "http://automation-project-chst.onrender.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]




# ===================== APPS =====================
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth

    # Third-party apps
    'dal',
    'dal_select2',
    'crispy_forms',
    'crispy_bootstrap5',
    'ckeditor',
    'django_browser_reload',
    'django_htmx',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',

    # Project apps
    'dataentry',
    'emails',
    'uploads',
    'accounts',  # Custom user model
    'notifications_app',
    'stockanalysis',
    'image_compression',
]


SITE_ID = 1

# ===================== AUTH =====================
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
)

# ===================== MIDDLEWARE =====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Allauth middleware (after SessionMiddleware & AuthMiddleware)
    'allauth.account.middleware.AccountMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]



# Configure crispy template pack

# ===================== TEMPLATES =====================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ROOT_URLCONF = 'automation_dj.urls'
WSGI_APPLICATION = 'automation_dj.wsgi.application'


# ===================== DATABASE =====================

USE_PRODUCTION_DB = False

if USE_PRODUCTION_DB:
    # DATABASES = {
    #     'default': dj_database_url.config(
    #         default='postgresql://automation_db_6m8m_user:bqBkpNO4FlwA1MelNJ6iO66Sc8UWxm0N@dpg-d330m3odl3ps738g1jb0-a.oregon-postgres.render.com/automation_db_6m8m',
    #         conn_max_age=600,    # optional, connection pooling
    #         # ssl_require=True 
    #     )
    # }

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'automation_db_6m8m',
            'USER': 'automation_db_6m8m_user',
            'PASSWORD': 'bqBkpNO4FlwA1MelNJ6iO66Sc8UWxm0N',
            'HOST': 'dpg-d330m3odl3ps738g1jb0-a.oregon-postgres.render.com',
            'PORT': '5432',
            'OPTIONS': {
                'sslmode': 'require',  # Render always requires SSL
            },
        }
        }

else:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }




# ===================== PASSWORD VALIDATION =====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===================== INTERNATIONALIZATION =====================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
# TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ===================== STATIC & MEDIA =====================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [BASE_DIR / 'automation_dj' / 'static', ]
# STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ===================== CRISPY =====================

CRISPY_TEMPLATE_PACK = "bootstrap5"


# ===================== MESSAGES =====================
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {messages.ERROR: "danger", 50: "critical"}

# ===================== CKEDITOR =====================
CKEDITOR_CONFIGS = {'default': {'height': 200}}

# ===================== EMAIL =====================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sojibhasan5800@gmail.com' 
EMAIL_HOST_PASSWORD = 'vpdilgkjbkoabmta'
# EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="sojibhasan5800@gmail.com")
# EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="password")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ===================== CELERY =====================

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ===================== CHANNELS =====================
ASGI_APPLICATION = 'automation_dj.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {"hosts": [('127.0.0.1', 6379)],},
    },
}

# ===================== DJANGO-ALLAUTH =====================

SOCIALACCOUNT_ADAPTER = 'accounts.adapter.CustomSocialAdapter'
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True


SOCIALACCOUNT_PROVIDERS = {
    # "google": {
    #     "APP": {"client_id": "", "secret": "", "key": ""},
    #     "SCOPE": ["profile", "email"],
    #     "AUTH_PARAMS": {"access_type": "online"},
    #     "EMAIL_AUTHENTICATION": True,
    # },
    "github": {
        "APP": {"client_id": "Ov23li3MowImdlx8hurj", "secret": "1910ed0e1a09ca0750a3bc495db30f4819d99e36", "key": ""},
        "SCOPE": ["user", "user:email"],
    },
    "facebook": {
        "APP": {"client_id": "777445715155003", "secret": "b2a2c0277c6a3481fcd99dcd13cdb439", "key": ""},
        "AUTH_PARAMS": {"auth_type": "reauthenticate"},
        "METHOD": "oauth2",
        "SCOPE": ["email"],
        "FIELDS": ["id", "email", "name", "first_name", "last_name"],
        "VERSION": "v12.0",
    },
}

# ===================== BASE URLS =====================

USE_PRODUCTION_URL = False
base_url = None
if USE_PRODUCTION_URL:
    BASE_URL="https://automation-project-chst.onrender.com"
else:
    BASE_URL = "http://127.0.0.1:8000"
